>xenopus_laevis
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MADHYQDYDSVGDHTAD-----------GSAQQIYTGGAGVHVLESSQE
SVIRLPSAAHGDDAASVQEELANGEAVRSQVRAQIPEGTTEEIALLATAGQEREPDTMA-
AAVKVTAHVEDYGITEEADGESQADKAAISSGVVES------------------------
-------ALEEDYYK--------ESNGKDVNLEICEEDTEGWEEQVDEGCEMRQDDEDEE
ELSPVEQPQTNG------------------------TGTDPIFLEDNKHEQKEIEEPYVD
IPASSFSVGQTRPRASVSVYQVEIDANIPINGKEAESEDVG-------------------
------------------------------------------IADTTEEKLKSPRKRVPA
HGSGIPVSRVPVPKAHEQEKHETDSQEKGAQISTKHPPAKHPSRLHTVPHKSPSSSTLKS
PSSPAASSVRSSQRTSLGTVGQLGITTRLHRAKEDGGPESATAKLTASRNTPTASRIPAK
TSSIPKTPPSTVRRDQRKAPSSMGKPDRESKSGERSGYSSPGSPGTPTGRSSS---QTPT
NREPKKIAVIRTPPKSPASAKSRLQPVTSPAAMPDLKNVRSKIGSTDNIRHQPGGGKVQI
VHKKVDLGNVQSKCGSKDNLKHVPGGGAIQITHKPIDLTRVTSKCGSFVNIHHKPGGGNV
ELKSEKLEF-DKIQSKIGSLDNVTHVPGGGAKKIESHKLSFRENAKAKTDHGAEIVYKSP
GHSGETSPRRLSNVSSSGSINMSNSPQLSTLADQVSASLAKQGL
>dipodomys_spectabilis
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MAEPRQEFDTAEDHAG-----------------------GYTLLHDQDG
------DTEHGLKESPLQTPADDGSEEPGSETSDAKSTPTAE------------------
--------AEEAGIGDTPNLEDQA------AGHVTQ------------------------
-------ARMVSKSK--------DGTGNDDKKA---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KGADGKTGTKIATPRGAATPG----------QKGAANATRIPAK
TTPSPKTPPGT---------------GESAKSGDRSGYSSPGSPGTPGSRSRTPSLPTPP
TREPKKVAVVRTPPKSPSSTKSRLQ--TAPVPMPDLKNVRSKIGSTENLKHQPGGGKVQI
INKKLDLSNVQSKCGSKDNIKHVPGGGSVQIVYKPVDLSKVTSKCGSLGNIHHKPGGGQV
EVKSEKLDFKDRVQSKIGSLDNITHVPGGGNKKIETHKLTFRENAKAKTDHGAEIVYKSP
VVSGDTSPRHLSNVSSTGSINMVDSPQLATLADEVSASLAKQGL
>gracilinanus_agilis
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MAEQRSSYNMMEDHTGNQQIHSGEPFQIGGERKDLASQGGYTLLQDNED
------DSGHGLKGYSQHTPADDGSDEQVSETSAKSTPTTEDVTAPLVDEQEHEDQPAAQ
VEIPEGTTAEEAGIGDTPNLEDQA------AGDVSQ------------------------
-------AR----KS--------SVAGSDEKKA---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KRAEAKSGIKMATHRAAMPSG----------QKGSANATRIPAK
TSG-PKTPPSA---------------GESTKSGERSGYSSPGSPGTPGSRSRTPSLPTPP
TREPKKVAVVRTPPKSPSSTKSRLQ--TSAVPMPDLKNVRSKIGSTENLKHQPGGGKVQI
FNKKLDLSNVQSKCGSKDNIKHVPGGGSVQIVYKPVDLSKVTSKCGSLGNIHHKPGGGQV
EVKSEKLDFKEKVQSKIGSLDNITHVPGGGNKKIESHKLTFRENAKAKTDHGAEIVYKSP
TMSGDTSPRHLSNVSSTGSINMVDSPQLATLADEVSASLAKQGL
>monodelphis_d0mestica
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MAEQRSSYNMMEDHSGNQQIHSGEPFQIGGERKDLASQGGYTLLQDNED
------DSGHGLKGYSQHTPADDGSDEQVSETSAKSTPTTEDVTAPLVDEQEHEDQPAAQ
VEIPEGTTAEEAGIGDTPNLEDQA------AGDVSQ------------------------
-------ARKS------------SVAGSDEKKV---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KRAESKSGIKMATHRAV-PSG----------HKGSANATRIPAK
ASG-PKTPPSA---------------GESTKSGERSGYSSPGSPGTPGSRSRTPSLPTPP
TREPKKVAVVRTPPKSPSSTKSRLQ--TSAVPMPDLKNVRSKIGSTENLKHQPGGGKVQI
FNKKLDLSNVQSKCGSKDNIKHVPGGGSVQIVYKPVDLSKVTSKCGSLGNIHHKPGGGQV
EVKSEKLDFKEKVQSKIGSLDNITHVPGGGNKKIESHKLTFRENAKAKTDHGAEIVYKSP
TMSGDTSPRHLSNVSSTGSINMVDSPQLATLADEVSASLAKQGL
>sarcophilus_harrisii
MRWGASARLSVPGNPGSRVGKGGIGVEIHGVWRGKERTTGGKGKKTCGRGDGETGGPRSR
SLEGSLWRPEEKTAAGKGGRLRRGVALALALALALRLSTCCLLWASAPALLLPLLLLLLP
LLLLLLSYSVRGEAPWSRTLILGCARPLSPTNTHLRPPSTATHRRRIRHRHHLFRAPHSP
RSGQAGNSLNRMAEQRPSFNMMEDHAGNQQIHSGEPFQIGGERKDMASQGGYTLLQDTED
------DTGHGLK-----------------------------------------------
--------AEEAGIGDTPNLEDQA------AGDVSQ------------------------
-------AR----KG--------SATGSDEKKA---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KGADNKSGIKMATPRTAAPSG----------QKGPANATRIPAK
TSA-PKTPPSA---------------GESTKSGDRSGYSSPGSPGTPGSRSRTPSLPTPP
TREPKKVAVVRTPPKSPSSAKSRLQ--TSTVPMPDLKNVRSKIGSTENLKHQPGGGKVQI
FNKKLDLSNVQSKCGSKDNIKHVPGGGSVQIVYKPVDLSKVTSKCGSLGNIHHKPGGGQV
EVKSEKLDFKEKVQSKIGSLDNITHVPGGGNKKIESHKLTFRENAKAKTDHGAEIVYKSP
TMSGDTSPRHLSNVSSTGSINMVDSPQLATLADEVSASLAKQGL
>dromiciops_gliroides
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MAEQRPSFSMMEDHTGSQQIHSGEPFQVGGERKDMPSQGGYTLLQDNED
------DTGHGLKGYSQHIPADDGSDEQVSETSAKSTPTTEDVTAPLVDEQEHEDQTATQ
VEIPEGTTAEEAGIGDTPNLEDQA------AGDVSQEEFRVSAECQREESEILDFLANEI
KSQMPQVSLEEAFQKPQIPLRKTEAEEPGMTVPLASQDSSMYSEVPRLDGDKAEQSLTSP
EPAVLESPKPSGYFRVGVEGSEVHQSFLSEHYGAEAIGQGAINMPGEEVSDRSAGSRPSQ
SPGDYPSVLPVKERAVVREDDEDRDVDESLPQDSPLPPQLSPIPVSLQPQEVALPSVTSR
ETVAIPHLPVEHHIRIPLPDDFLSKISPEMPVIERDLPAVGQVATEGSDGLSSLELSEGV
FHVDIKPNIPKEQEFSELGPEDSLSGEPGSPSASVEVDAKTPEKQPVRSPSGKPVSRVPQ
LKARKGSATGSDEKKAKGAETKSGMKMGTPRAAAPSG----------QKGPANATRIPAK
TSA-PKTPPSA---------------GESTKSGDRSGYSSPGSPGTPGSRSRTPSLPTPP
TREPKKVAVVRTPPKSPSSAKSRLQ--TSTVPMPDLKNVRSKIGSTENLKHQPGGGKVQI
FNKKLDLSNVQSKCGSKDNIKHVPGGGSVQIVYKPVDLSKVTSKCGSLGNIHHKPGGGQV
EVKSEKLDFKEKVQSKIGSLDNITHVPGGGNKKIESHKLTFRENAKAKTDHGAEIVYKSP
TMSGDTSPRHLSNVSSTGSINMVDSPQLATLADEVSASLAKQGL
>vombatus_ursinus
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MAEQRPSFSMMEDHPGNQQIHSGEPFQIGGERKDMPSQ-GYTLLQDSED
------DTGHGLKGYTPQTPADDGSDEQVSEISAKSTPTTEDVTAPLVDEQEHEDQTAAQ
VEIPEGTTAEEAGIGDTPNLEDQA------AGDVSQ------------------------
-------AR----KS--------SAAGSDEKKA---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------KTSTPS
SAQTFLKGRPTIIPKRPSPVSSDPSITPSSPAVSSVPGSSPKHVSSVTSHTGSSGAKAMK
P---------------KGAETKSGIKMATPRAAAPSG----------QKGPANATRIPAK
TSA-PKTPPSA---------------GESTKSGDRSGYSSPGSPGTPGSRSRTPSLPTPP
TREPKKVAVVRTPPKSPSSAKSRLQ--TSTVPMPDLKNVRSKIGSTENLKHQPGGGKVQI
FNKKLDLSNVQSKCGSKDNIKHVPGGGSVQIVYKPVDLSKVTSKCGSLGNIHHKPGGGQV
EVKSEKLDFKEKVQSKIGSLDNITHVPGGGHKKIESHKLTFRENAKAKTDHGAEIVYKSP
TMSGDTSPRHLSNVSSTGSINLVDSPQLATLADEVSASLAKQGL
>N._eugenii
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------LSG----------QKGSSNATRIPAK
TSA-PKTPPSA---------------GESTKSGDRSGYSSPGSPGTPGSRSRTPSLPTPP
TREPKKVAVVRTPPKSPSSAKSRLQ--TSTVPMPDLKNVRSKIGSTENLKLQPGGGKVQI
FNKKLDLSNVQSKCGSKDNIKHVPGGGSVQIVYKPVDLSKVTSKCGSLGNIHHKPGGGQV
EVKSEKLDFKEKVQSKIGSLDNITHVPGGGHKKIESHKLTFRENAKAKTDHGAEIVYKPP
TMSGDTSPRHLSNVSSTGSINMVDSPQLATLADEVSASLAKQGL
>trichosurus_vulpecula
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------MAEQRPSFSMLEDHAGNQQIHSGEPFQIGGERKDMPSQGGYTLLQDSED
------DTGHGLK-----------------------------------------------
--------AEEAGIGDTPNLEDQA------AGDVSQ------------------------
-------AR----KG--------SATGSDEKKA---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------KGAETKSGIKMATPRAGAPSG----------QKGSANATRIPAK
TSA-PKTPPSA---------------GESTKSGDRSGYSSPGSPGTPGSRSRTPSLPTPP
AREPKKVAVVRTPPKSPSSAKSRLQ--TSTVPMPDLKNVRSKIGSTENLKHQPGGGKVQI
FNKKLDLSNVQSKCGSKDNIKHVPGGGSVQIVYKPVDLSKVTSKCGSLGNIHHKPGGGQV
EVKSEKLDFKEKVQSKIGSLDNITHVPGGGHKKIESHKLTFRENAKAKTDHGAEIVYKSP
TMSGDTSPRHLSNVSSTGSINMVDSPQLATLADEVSASLAKQGL
